export const Icons  = {
    CENTER: 'a',
    PAINT: 'b',
    FOLDER: 'c',
    CUBE: 'd',
    GAME: 'e',
    MOVE: 'f',
    ROTATE: 'h',
    SCALE: 'g',
    SAVE: 'i',
    TRASH: 'j',
    NEW_IMAGE: 'k',
    MIN_CUBE: 'l',
    PLUS_CUBE: 'm',
    SELECT: 'n',
    SELECT_FULL: 'o',
    BEZIER: 'q',
    LINE: 'p',
    CLOSE: 'r',
    NEXT: 's',
    DELETE_IMAGE: 't',
    ADD_ANIME: 'u',
    REMOVE_ANIME: 'v',
    DOWN_ARROW: 'w',
}
