export const Icons  = {
    CENTER: 'a',
    PAINT: 'b',
    FOLDER: 'c',
    CUBE: 'd',
    GAME: 'e',
    MOVE: 'f',
    ROTATE: 'h',
    SCALE: 'g',
    SAVE: 'i',
    TRASH: 'j',
    NEW_IMAGE: 'k',
    MIN_CUBE: 'l',
    PLUS_CUBE: 'm',
}
