//generated by server

export var ModelNames = {
TEST_TREE: 'test_tree',
TEST_BUSH: 'test_bush',
TEST_SUN: 'test_sun',
TESTCHARACTERS_PINK: 'testCharacters_pink',
TESTCHARACTERS_BLUE: 'testCharacters_blue',
TESTCHARACTERS_GREEN: 'testCharacters_green',
TESTOBJECTS_CLOUD1: 'testObjects_cloud1',
TESTOBJECTS_CLOUD2: 'testObjects_cloud2',
TESTOBJECTS_BODY: 'testObjects_body',
TESTOBJECTS_EYE: 'testObjects_eye',
TESTOBJECTS_FEET: 'testObjects_feet',
TESTOBJECTS_FEET2: 'testObjects_feet2',
TESTOBJECTS_GRASS1: 'testObjects_grass1',
TESTOBJECTS_GRASS2: 'testObjects_grass2',
TESTOBJECTS_GRASS3: 'testObjects_grass3',
TESTOBJECTS_FLOWERCIRCLE: 'testObjects_flowerCircle',
TESTOBJECTS_FLOWERLEAVES: 'testObjects_flowerLeaves',
TESTOBJECTS_FLOWERSTEM: 'testObjects_flowerStem',
TESTOBJECTS_HANDRIGHT: 'testObjects_handRight',
TESTOBJECTS_HANDLEFT: 'testObjects_handLeft',
}