//generated by server

export var ModelNames = {
TEST_TREE: 'test_tree',
TEST_BUSH: 'test_bush',
TEST_SUN: 'test_sun',
TESTCHARACTERS_PINK: 'testCharacters_pink',
TESTCHARACTERS_BLUE: 'testCharacters_blue',
TESTCHARACTERS_GREEN: 'testCharacters_green',
}